import Head from 'next/head';
import { BsFillMoonStarsFill, BsFillSunFill } from 'react-icons/bs';
import { AiFillLinkedin, AiFillGithub, AiFillTwitterCircle, AiFillMediumCircle,AiFillHtml5 } from 'react-icons/ai';
import { DiCss3, DiNodejsSmall, DiRuby } from 'react-icons/di';
import { FaGitAlt } from 'react-icons/fa'
import { SiJavascript, SiTailwindcss, SiTypescript, SiRedux, SiExpress, SiPostgresql, SiSequelize, SiRubyonrails, SiPython } from 'react-icons/si';
import { GrReactjs } from 'react-icons/gr';
import Image from "next/image";
import deved from '../public/dev-ed-wave.png';
import web1 from '../public/web1.png';
import web2 from '../public/web2.png';
import { useState } from 'react';

export default function Home() {
  const [darkMode, setDarkmode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
    <Head>
      <title>Alejandro Quintero Mejia Portfolio</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main className='bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900'>
      <section className='min-h-screen'>
        <nav className='py-10 mb-12 flex justify-between'>
          <h1 className='text-xl font-burtons dark:text-white'>Welcome!</h1>
          <ul className='flex items-center gap-2.5'>
            <li onClick={() => setDarkmode(!darkMode)} className='cursor-pointer text-2xl dark:text-white'>
              {!darkMode ? <BsFillMoonStarsFill  /> : <BsFillSunFill/>}
              </li>
            <li><a className='bg-teal-600 text-white px-4 py-2 rounded-md ml-8' href='../public/resume.pdf' target='_blank' rel="noreferrer">Resume</a></li>
          </ul>
        </nav>
        <div className='text-center p-10'>
          <h2 className='text-5xl py-2 text-teal-600 font-medium md:text-6xl'>Alejandro Quintero Mejia</h2>
          <h3 className='text-2xl py-2 md:text-3xl dark:text-white'>Web Developer and Mathematician</h3>
          <p className='text-md py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto dark:text-white'>I like to combine the skill and tools acquired in both profiles, in order to efficiently resolve the different challenges present in tech. I am in love with 
          <span className='text-teal-500'> Software Development, Blockchain</span> and <span className='text-teal-500'> Artificial Intelligence</span>
          </p>
        </div>
        <div className='text-5xl flex justify-center gap-16 py-1 text-gray-800 dark:text-white'>
          <a href='https://github.com/AlejoMejia96' target='_blank' rel="noreferrer" ><AiFillGithub /></a>
          <a href='https://www.linkedin.com/in/alejandro-quintero-mejia' target='_blank' rel="noreferrer"><AiFillLinkedin /></a>
          <a href='	https://medium.com/@alejandroquinteromejia' target='_blank' rel="noreferrer"><AiFillMediumCircle /></a>
          <a href='https://twitter.com/BatmathDev' target='_blank' rel="noreferrer"><AiFillTwitterCircle /></a>
        </div>
        <div className='relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-10 overflow-hidden md:h-96 md:w-96'>
          <Image src={deved} layout='fill' objectFit='cover'/>
        </div>
      </section>

      <section>
        <div className='text-center p-10'>
          <h3 className='text-3xl py-5 pb-10 dark:text-white'>Technologies I use</h3>
          <div className='text-5xl grid grid-rows-3 grid-flow-col gap-8 justify-center py-3 text-gray-800 md:grid-rows-2 dark:text-white'>
            <SiJavascript />
            <DiCss3 />
            <SiSequelize />
            <SiTypescript />
            <SiTailwindcss />
            <SiPython/>
            <GrReactjs />
            <DiNodejsSmall />
            <DiRuby />
            <SiRedux />
            <SiExpress />
            <SiRubyonrails />
            <AiFillHtml5 />
            <SiPostgresql />
            <FaGitAlt />
          </div>
        </div>
        <div>
          <div className='text-center p-5'>
          <h3 className='text-3xl dark:text-white'>Projects</h3>
          </div>
          <div className='flex flex-col lg:flex-row lg:flex-wrap lg:gap-10'>
            <div className='basis-1/3 flex-1 text-center shadow-lg p-5 py-5 rounded-xl my-10 dark:bg-teal-600'>
            <h4 className='pb-5 text-teal-600 dark:text-white'>Tech Store E-commerce</h4>
              <a href='https://tech-store-prod.vercel.app/' target="_blank" rel="noreferrer"><Image src={web2} className='rounded-lg object-cover width={"100%"} height={"100%"} layout="responsive" '/></a>
              <p className='text-md pt-5 leading-8 text-gray-800 dark:text-white'>The project consists of a <span className='text-teal-600 dark:text-gray-900'>virtual store of technological articles.</span> On it you can find products by categories that can be filtered by shipping cost, price range and in ascending and descending order, as well as added to a wishlist or directly to a shopping cart.
              </p>
              <p className=' flex justify-center gap-2 text-2xl py-5 leading-5 text-gray-800 dark:text-white'> 
                <SiJavascript />
                <AiFillHtml5 />
                <SiTailwindcss />
                <GrReactjs />
                <SiRedux />
                <SiExpress />
                <SiSequelize />
                <SiPostgresql />
              </p>
              <p><a className='bg-teal-600 text-white px-4 py-2 rounded-md dark:bg-gray-900 dark:justify-center dark:px-4 dark:py-2 dark:rounded-md' href='https://github.com/stars/AlejoMejia96/lists/tech-store' target='_blank' rel="noreferrer">Source code</a></p>
            </div>
            <div className='basis-1/3 flex-1 text-center shadow-lg p-5 py-5 rounded-xl my-10 dark:bg-teal-600'>
              <h4 className='pb-5 text-teal-600 dark:text-white'>Dogs App</h4>
              <a href='https://dogs-app-jade.vercel.app/' target="_blank" rel="noreferrer"><Image src={web1} className='rounded-lg object-cover width={"100%"} height={"100%"} layout="responsive"'/></a>
              <p className='text-md pt-5 leading-8 text-gray-800 dark:text-white'>The project consists of a <span className='text-teal-600 dark:text-gray-900'>SPA (Single Page Application) </span>that consumes data from an API and allows both the visualization, filtering and sorting of more than 150 dog breeds, as well as the possibility of creating new breeds and adding them to a database.
              </p>
              <p className=' flex justify-center gap-2 text-2xl py-5 leading-5 text-gray-800 dark:text-white'> 
                <SiJavascript />
                <AiFillHtml5 />
                <DiCss3 />
                <GrReactjs />
                <SiRedux />
                <SiExpress />
                <SiSequelize />
                <SiPostgresql />
              </p>
              <p><a className='bg-teal-600 text-white px-4 py-2 rounded-md dark:bg-gray-900 dark:justify-center dark:px-4 dark:py-2 dark:rounded-md' href='https://github.com/stars/AlejoMejia96/lists/dogs-app' target='_blank' rel="noreferrer">Source code</a></p>
            </div>
          </div>
        </div>
      </section>
    </main>
  </div>
  )
}
